CONFUCIUS = [
         'confucius say, man who lose key to girlfriends apartment get no new key',
         'confucius say, man who go to bed with itchy butt wake up with stinky finger',
	 'confucius say, man who fart in church must sit in own pew',
	 'confucius say, man who walk thru airport turnstile sideways going to bangkok',
	 'confucius say, passionate kiss like spiders web, soon lead to undoing of fly',
	 'confucius say, man who stand in front of car get tired',
	 'confucius say, virginity like bubble, one prick all gone',
	 'confucius say, man who stand behind car get exhausted',
	 'confucius say, man with hand in pocket feel cocky',
	 'confucius say, foolish man give wife grand piano, wise man give wife upright organ',
	 'confucius say, man who buy many prunes get good run for money',
	 'confucius say, baseball wrong, man with four balls no can walk',
	 'confucius say, wife who put husband in doghouse soon find him in cathouse',
	 'confucius say, it take much wood to build crib but one screw to fill it',
	 'confucius say, man who fishes in other mens wells often catch crabs',
	 'confucius say, man who masturbate into cash register soon cum into money',
	 'confucius say, person who drop watch in toilet have shitty time',
	 'confucius say, man who fight with wife all day get no piece at night',
	 'confucius say, person who sells lady pads is crack salesman',
	 'confucius say, man who play with titty gets bust in mouth',
	 'confucius say, person who drive and eat ice cream is sundae driver',
	 'confucius say, one who sit on hot stove will soon rise',
	 'confucius say, person who jump off cliff soon arrive at conclusion',
	 'confucius say, womans breast without nipple is pointless',
	 'confucius say, he who drop watch in whiskey waste time',
	 'confucius say, man kicked in testicles left holding bag',
	 'confucius say, house without toilet seem uncanny',
	 'confucius say, if oriental get turned around he become disoriented',
	 'confucius say, better to meat girl in park than meet girl in park',
	 'confucius say, man who eat photo of father soon spitting image of father',
	 'confucius say, person who masterbate only screwing self',
	 'confucius say, man who put cock on stove have hot rod',
	 'confucius say, man like spider soon have sticky hand from being on web',
	 'confucius say, man who read book on women prefer book in braille',
	 'confucius say, one who sit on tack get point',
	 'confucius say, woman who douches with vingar walk around with sour puss',
	 'confucius say, man with hand in bush not always trimming shrubs',
	 'confucius say, squirrel who run up womans leg not find nuts',
	 'confucius say, boy who play with girl in wrong period get caught red handed',
	 'confucius say, woman who fly plane upside down have crack up',
	 'confucius say, he who is a master fisherman was once a master baiter',
	 'confucius say, person who cross ocean twice without washing is dirty double crosser',
	 'confucius say, one who go to bed with sex problem wake up with solution in hand',
	 'confucius say, man who suck womans nipples soon make clean breast of things',
	 'confucius say, grease monkey who go to bed without bathing wake up oily in morning',
	 'confucius say, never tell pig a secret it may squeal',
	 'confucius say, girl who slide down banister make monkey shine',
	 'confucius say, nail on board not good as screw on bench',
	 'confucius say, man who marry woman with big hands make dick look smaller',
	 'confucius say, man may have dick but not need be one',
	 'confucius say, man who have hand in pocket not crazy just feeling nuts',
	 'confucius say, woman like a convertable more fun with top down',
	 'confucius say, cross eyed teach cannot control pupils',
	 'confucius say, person who find no magic in bed soon dissapear',
	 'confucius say, person who streak not suitable for work',
	 'confucius say, person looking for helping hand need look at end of own arm',
	 'confucius say, girl who sit on lap of judge get honorable discharge',
	 'confucius say, politician shake hand before election and confidence after',
	 'confucius say, good for girl to meet boy in park but better for boy to park meat in girl',
	 'confucius say, man who try doggie style sex not want to face wife again',
	 'confucius say, nobel prize sperm sample is stroke of genius',
	 'confucius say, woman who love elevator operator always get shaft',
	 'confucius say, man who want peace on earth lay woman on ground',
	 'confucius say, lawyer who join nudist colony have no more suits',
	 'confucius say, better to kiss snatches than snatch kisses',
	 'confucius say, he who thinks by the inch and talks by the yard deserves to be kicked by the foot',
	 'confucius say, vagina like small motel must leave bag outside',
	 'confucius say, teenager in prison never stop face from breaking out',
	 'confucius say, virgin who sleep on waterbed get called cherry float',
	 'confucius say, person who have head up ass have shitty outlook on life',
	 'confucius say, lying fisherman catch fish by the tale',
	 'confucius say, best defense against rapist is beat off attacker',
	 'confucius say, dont let affection make infection put protection on erection',
	 'confucius say, political speeches like bicycle wheel the longer spoke the more tired',
	 'confucius say, never argue with woman that packs your parachute',
	 'confucius say, undertaker is last person to let you down',
	 'confucius say, always remove fortune before eating cookie',
	 'confucius say, turtle only progress when stick neck out',
	 'confucius say, tight dress like barbed wire fence protect property and leave great view',
	 'confucius say, best way to keep word is not give it',
	 'confucius say, cow with no legs is ground beef',
	 'confucius say, mrs dumpty gives humpty egghead',
	 'confucius say, two wrongs no make right but three lefts do',
	 'confucius say, if shoe fit get another just like it',
	 'confucius say, some people are like fish no trouble if keep mouth shut',
]

class Confucius < Plugin
    def help(plugin, topic="")
        "confucius => random confucius says quotes."
    end

    def confucius(m, params)
        m.reply CONFUCIUS.pick_one
    end
end

plugin = Confucius.new
plugin.map 'confucius'