NUKEM = [
    'AAhhh... much better! (after urinating)',
    'Bitchin\'!',
    'Blow it out your ass! (referencing They Live)',
    'Boooorn tooo beee wiiiiiiild... (singing badly at karaoke)',
    'Come get some! (reference to Ash\'s quote from Army of Darkness) (says after choosing the hard difficult setting)',
    'Come on! (after the player was not moving for a while)',
    'Damn....',
    'Damn!',
    'Damn it. (after killing any of the women in the game)',
    'Damn, I\'m good! (says after choosing the "Damn, I\'m Good" difficult setting)',
    'Damn... I\'m looking good! [after looking at himself in a mirror]',
    'Damn, those alien bastards are gonna pay for shooting up my ride. (after the aliens destroy his monter truck)',
    'Damn, that\'s the second time those alien bastards shot up my ride!',
    'Damn, you\'re ugly. [in reference to Predator]',
    'Do, or do not, there is no try. [in reference to Yoda]',
    'Eat shit and die.',
    'Get away from her, you bitch! (in reference to Aliens)',
    'Get that crap outta here! [After an enemy dies violently (exploding)]',
    'Die, you son of a bitch! (after defeating the Battlelords, in reference to Jaws)',
    'Get back to work, you slacker! (checking out office computer playing Duke3d)',
    'Go ahead, make my day. (reference to the same phrase from Clint Eastwood\'s character Dirty Harry in the film Sudden Impact)',
    'Gonna rip \'em a new one.',
    'Guess again, freakshow. I\'m coming back to town, and the last thing that\'s gonna go through your mind before you die... is my size-13 boot!',
    'Groovy! [reference to Ash\'s quote from Evil Dead 2:Dead by Dawn]',
    'Hail to the king, baby! [reference to Ash\'s quote from Army of Darkness]',
    'Heh, heh, heh... what a mess! [After an enemy dies violently (exploding)]',
    'Hey, She-bitch...let\'s rock! [Ash quote from Army of Darkness]',
    'HHHHHHHHHHHEEEEEEEEEEAAAAAAAAAAAHHHHHHHHHHHH!!!!!!! [Falling to his death]',
    'Hmm, don\'t have time to play with myself. [Duke examines the Duke Nukem II arcade machine]',
    'Hmm, that\'s one "Doomed" Space Marine. [seeing a torn corpse of a Space Marine from Doom]',
    'Holy cow!',
    'Holy shit!',
    'I\'ll rip your head off and shit down your neck. (reference to Gunnery Seargeant Hartman in the movie Full Metal Jacket and also appeared in the 1986 movie Stand By Me, and earlier in the 1983 movie, Doctor Detroit)',
    'I\'m gonna get medieval on your asses!',
    'I\'m gonna kick your ass, bitch!',
    'I\'m gonna put this smack dab on your ass!',
    'I ain\'t afraid of no quake! (in reference to ID Software\'s Quake PC Game, as well as Ghostbusters tagline)',
    'I like a good cigar...and a bad woman...',
    'I should have known those alien maggots booby-trapped this sub.',
    'It\'s time to kick ass and chew bubble gum... and I\'m all outta gum. (reference to They Live)',
    'It\'s down to you and me, you one-eyed freak! (when encountering the Emperor)',
    'It\'s time to abort your whole freaking species! (After defeating the Queen)',
    'Let God sort \'em out! (Advice given by Arnaud Amalric during the Albigensian Crusade when asked by a Crusader how to distinguish the Cathars from the Catholics)',
    'Let\'s rock! (Possible reference to Vasquez in Aliens)(says after choosing the medium difficult setting)',
    'Looks like cleanup on aisle four. (Possible reference to Ash in Army of Darkness)',
    'Lucky son of a bitch.',
    'Mess with the best, you will die like the rest (reference to Hackers (1995))',
    'My boot, your face, the perfect couple.',
    'My name is Duke Nukem - and I\'m coming to get the rest of you alien bastards! (After defeating the Battlelord)',
    'No way I\'m eating this shit!',
    'Nobody steals our chicks... and lives!',
    'Now this is a force to be reckoned with! (after discovering a Stormtrooper\'s corpse hanging upside down] (reference to Dark Forces)',
    'Nuke \'em \'till they glow, then shoot \'em in the dark!',
    'Oh...your ass is grass and I\'ve got the weed-whacker.',
    'Ooh, I needed that! [After gaining health when less than 25%]',
    'Ooh, that\'s gotta hurt. (says sarcastically after blowing up enemy corpses) [Possible reference to Ash in Army of Darkness]',
    'Piece of Cake. (says after choosing the "Piece of Cake" difficulty)',
    'See you in Hell!',
    'Shake it, baby! (after handing a girl money)',
    'Shit happens. (after stepping in alien feces, reference to Forrest Gump or Predator 2)',
    'Sometimes I even amaze myself. (In reference to Star Wars)',
    'Staying alive, staying alive, la. (singing Bee Gees \'Staying Alive\')',
    'Suck it down!',
    'Terminated! (after discovering the hydraulic press with the crushed Terminator skeleton in the secret \'Freeway\' level)',
    'This really pisses me off!',
    'This is KTIT, K-Tit! Playing the breast- uhh, the best tunes in town.',
    'That\'s gonna leave a mark!',
    'We meet again, Doctor Jones! (after discovering Indiana Jones corpse hanging)',
    'What are you waitin\' for? Christmas? (after the player has been away from keyboard for a while) (reference to Die Hard)',
    'What are you? Some bottom-feeding, scum-sucking algae eater?',
    'Where is it?',
    'Who wants some? (reference to Ash\'s quote from Evil Dead 2)',
    'Wohoo!',
    'Yeah, piece of cake!',
    'Yippie ka-yay, motherfucker! [reference to Bruce Willis, from the Die Hard Films)',
    'You guys suck!',
    'You\'re an inspiration for birth control.',
    'Your face, your ass - what\'s the difference? (reference to an Andrew Dice Clay joke)',
    'You wanna dance? (after handing a girl money)',
    'COME GET SOME!!!',
    'Dying ain\'t much of a living boy. (Reference to Clint Eastwood in The Outlaw Josey Wales)',
    'Eat shit and die bitch!',
    'Your face, your ass - what\'s the difference? (again, reference to an Andrew Dice Clay joke)',
    'Friends, Romans, countrymen, lend me your chicks. (When duke travels to the Roman Story)',
    'Have you seen my rubber...duckie?',
    'Hello McFly (Back to the Future reference)',
    'Hey! Get your ass out of here, Rubbe, and bring me back my chicks! (to a male stripper)',
    'I\'ll blow you a new hole!',
    'I\'m God\'s gift to women!',
    'Get to the chopper! (Reference to Predator)',
    'I love the smell of bacon in the morning (Reference to Apocalypse Now and the quote "I love the smell of the napalm in the morning")',
    'I make this look good. [Reference to Men in Black]',
    'Lara, is that you? [after picking up a pay phone and listening to a moaning babe/Reference to Tomb Raider\'s Lara Croft]',
    'Looks like it\'s TIME TO KILL! (when you 1st start the game) (Reference to Caleb, character of Blood I game by Monolith Productions)',
    'My home away from home! [in reference to a strip club]',
    'Suck my boomstick (After killing an enemy with a shotgun/ Reference to the Evil Dead series.)',
    'The bigger they are, the more they bleed!',
    'There\'s a new sheriff in town. (pronounced in a southern accent when in the western story)',
    'You\'ll make a great belt (after killing a lizard)',
    'Little pig, Little pig let me in. Or I\'ll huff and I\'ll puff and I\'ll kick your ass in! [Reference to the "Three Little Pigs"]',
    'Rubba dub dub getta out of the tub.',
    'It\'s Locked, an I\'m an ass kicker not a safe cracker.',
    'Mmmm! Who wants bacon and eggs? (after killing Pig Cops)',
    'Has anyone seen Mr. Hanky? (after jumping down a well in the western story) [Reference to South Park and the character Mr. Hanky from the episode "The Christmas Poo" ]',
    'Is it true that Roman girls have Roman hands?',
    'Lizard skin makes great boots',
    'Not in this lifetime! (if you press X while he\'s standing in front of a male poledancer.)',
    'I\'ve got balls of steel.',
    'I\'ve got a Lizard in my boot (after kicking a lizard) (reference to Toy Story\'s "There\'s a snake in my boot!")',
    'Where\'s Doc\' Brown when Ya need him? (Refering to the time traveler Doc Brown from the Back to the Future series)',
    'Who wants some?',
    'Hey what can I say',
    'Come on!',
    'All aboard!',
    'Knight me or bite me, man!',
    'Let\'s settle this once and for all!',
    'I\'ll kick you in the "nuts"!',
    'Oh Yeah!',
    'I prefer a good cigar and a bad woman',
    'Ahhhhhhhh!',
    'Shake it baby!',
    'Hey baby wanna use some lotion!',
    'Let do get you out of those wet clothes baby!',
    'It\'s Locked, an I\'m an ass kicker not a lock picker',
    'Die you overgrown winged lizard from Hell!',
    'Shut you your hole!',
    'What are you waiting for, Christmas?',
    'Been there, done that',
    'Heard you ain\'t been getting...Nun',
    'Blow it out your knees! (reference to Duke Nukem 3D)',
    'Don\'t worry about it, saving chicks is what I\'m all about!',
    'I ain´t got time to bleed! (reference to Predator)',
    'Who the hell are you? My evil twin? (Talking to future self)',
    'Alien boys, there\'s a new sheriff in town.',
    'I don\'t die that easy boys. Come on time for a jail break.... by balls.',
    'It ain\'t no bike, but? it sure beats the hell outta walking.',
    'Squeal piggy ! Squeal shove it in here ! [reference to Deliverance]',
    'Oh boy, it\'s clobberin\' time! [reference to The Thing from Marvel\'s Fantastic Four]',
    'Eh... Just a flesh wound. [reference to Monty Python and the Holy Grail]',
    'nuts roasting... as I open fire (In reference to the Christmas carol Chestnuts roasting ON an open fire)',
    'Ahhh, smell those traffic fumes. And no damn aliens! Time for some R & R!',
    'Hey kids you remember I\'m a professional, don\'t try this at home!',
    'What the *bleep* (f**k) is goin\' on here?!',
    'This won\'t buuuudge.',
    'Looks like the crap has hit the fan. (upon arriving at the thrashed Duke Burger)',
    'Female Commander: New York is in trouble Duke, the alien scum have taken over of the area around Liberty Island. Without immediate intervention they\'ll get the whole damn city. Your helicopter is waiting, go kick some ass...',
    'Marine: I\'m cocked, locked, and ready to rock! [reference to The Rock]',
    'Mess with the best, die like the rest ( It\'s a quote from the movie "Hackers )',
    'I\'m sorry, did I break your concentration? (Reference to "Pulp Fiction")',
    'Well, enough talk then. Come get some! Oh, Silverback, one more thing. I\'m gonna enjoy pissin\' on your dead body!',
    'Welcome to "Cool\'s-Ville", Population: Me. [reference to The Iron Giant]',
    'I\'m your worst nightmare, you uninvited alien scum-sucker! And right now you\'re all that stands between me and a planet full of babes - so get ready to bend over and kiss your ass goodbye!',
    'I\'m climbing a ladder........to heaven. [reference to Led Zeppelin\'s Stairway to Heaven.]',
    'Suck my dick you little alien fucks!',
    'That hurt you more than it hurt me.',
    'Damn you\'re ugly!',
    'Bug off!',
    'You guys suck!',
    'The Bigger they are the harder they fall',
    'Ah, New York! It\'s my kind of town. If I can kill \'em here...I can kill \'em anywhere! / Reference to Frank Sinatra\'s song "New York" ("If I can make it there, I\'ll make it anywhere...")',
    'Babe: "Duke, you\'re my hero!" Duke: "You must be 18 or older to ride."',
    'Babes, bullets, bombs. Damn - I love this job!',
    'Batteries not included! (after killing a robot/mech)',
    'Come on out, Morphix. There\'s just two ways this can end, and in both of them, you die!',
    'Confucius say... DIE!',
    'Crouching mutant, hidden pipebomb! (reference to the chinese proverb "crouching tiger hidden dragon")',
    'Dance for me, baby!',
    'Death before Disco! (when Duke enters E2L3)',
    'Die bitch! (when duke shoots a female bot)',
    'Don\'t get your panties all in a bunch.',
    'Guns don\'t kill mutants, I kill mutants.',
    'Half man, half animal, all dead. (Reference to Robocop: "Half man, Half machine, all cop")',
    'Hey, careful with those things! (after rescuing a babe)',
    'Hmm, so there is life after death... (after respawning)',
    'Hmmm... That\'s gonna leave a mark. (when he blows up enemies)',
    'Hmmm...the other white meat (when Duke encounters a pig cop)',
    'I always said, if there was a way to go, it\'d have something to do with women, whips, and oil...',
    'I am king of the world, baby! (reference to the 1997 film "Titanic")',
    'I\'m? an equal opportunity asskicker!',
    'I\'m? not gonna fight you, I\'m gonna KICK YOUR ASS!',
    'I can do this all day... (after respawning)',
    'I could use some new boots. (when Duke encounters a mutant crocodile)',
    'I don\'t do windows (when encountering window cleaning platforms)',
    'I go where I please, and I please where I go. (after rescuing a babe)',
    'I hate pigs! (after killing a pig cop)',
    'I kill bugs...DEAD! (after killing a mutant roach or fly, old Raid insect killer slogan)',
    'I like big guns, and I cannot lie. (when rocket launcher is selected, reference to Sir Mix-A-Lot\'s song "Baby Got Back")',
    'I love the smell of burnt crap in the morning. (reference to the film Apocalypse Now: "I love the smell of napalm in the morning")',
    'I see dead people. (when he blows up enemies, reference to the film The Sixth Sense)',
    'It\'s a good day to die! (reference to Worf from Star Trek: The Next Generation)',
    'It\'s clobbering time! (when double damage is picked, Reference to "The Thing" of the "Fantastic Four")',
    'It\'s my way or... Hell, it\'s my way! (After blowing up a subway car)',
    'It\'s scares tripping time!',
    'Keycards? (when a keycard is needed to open the door)',
    'Let\'s rock! (before engaging the the final fight with Morphix)',
    'Life is like a box of ammo. (when assult rifle is selected, reference to the film Forrest Gump: "Life is like a box of chocolates...")',
    'Looks like I\'m on Candy Camera (allusion to a tv-show pranking people)',
    'Looks like your hardware\'s gone a little soft, Morphix! (when trashing Morphix\'s robot)',
    'Makin\'...bacon! (after killing a pig cop)',
    'Morphix and his glop rig are going down faster than Enron. (Reference to the bankrupt Enron Corporation)',
    'Mother F-[beep] keycards! (when a keycard is needed to open the door...again)',
    'My gun\'s bigger than yours. (when pulse cannon is selected)',
    'No token, no ride! [when he kills a mutant on the subway] (reference to Indiana Jones "Zeppelin Scene")',
    'No disassembling required. (after killing a robot/mech)',
    'Now I\'m really pissed off! (after respawning)',
    'Oops, I did it again! (when he blows up enemies, reference to the Britney Spears song)',
    'Pucker up, buttercup! (when Duke encounters a fembot)',
    'Rest in pieces! (when he blows up enemies)',
    'Say "hello" to my little friend! (when pipebombs are selected, reference to "Scarface")',
    'Sewer scum! (when Duke encounters a mutant rat)',
    'Should\'ve stayed in the swamp! (after killing a mutant crocodile)',
    'So many babes, so little time.',
    'So much for the rat pack! (after killing a mutant rat)',
    'So, who wants to dance?! (after rescuing a babe)',
    'Someone\'s gonna pay for making me find these friggin\' key cards... (when a keycard is needed to open the door...yet again)',
    'Son of a bitch! (after respawning, blowing up enemies, or when soda machines don\'t work)',
    'Sorry, honey, I\'ve got some asskickin\' to do first! (when saving a babe)',
    'Squeal like a pig! (when Duke encounters a pig cop)(reference from "Deliverence")',
    'Stop eyeballin\' me! (when Duke encounters a flying camera)',
    'Surprise, surprise, I need a keycard. (when a keycard is needed to open the door...again)',
    'Take that, you dirty rat! (after killing a mutant rat)',
    'This is why I have games named after me!',
    'Time for mutation-mutilation! (when GLOPP ray is selected)',
    'Time for a reboot! (when Duke encounters a robot/mech)',
    'Time to deliver max pain on the A-Train...now where\'d I put that subway token? (A reference to the video games Max Payne and A-Train)',
    'Time to deworm the Big Apple...',
    'This\'ll be a barrel of laughs (when shotgun is selected)',
    'This room is bugged (when Duke encounters a mutant roach or fly)',
    'What a pussy! (after killing a fembot)',
    'What am I? A frog? (reference to the game Frogger as Duke tries to run between cars)',
    'Who wants to glow in the dark? (when GLOPP ray is selected)',
    'You\'re goin\' down faster than the XFL! (Reference to the short-lived XFL Football League)',
    'You\'re starting to bug me. (after killing a mutant insect)',
    'You are the missing link. Goodbye. (Reference to the game show The Weakest Link -- or to the "missing link" species between ape and human in misunderstood evolution theory)',
    'Your kung-fu\'s through! (after killing a mutant crocodile)',
    'You talkin\' to me? (reference to Taxi Driver)',
    'Space, the final frontier. These are the voyages of Duke Nukem. My continuing mission: to explore strange new babes, to seek out new aliens and kick their asses. (Reference to the TV series "Star Trek")',
    'I oughta break a broomhandle off in your ass.',
    'I was born to rock the world!(E3 trailer, 1998)',
    'Always bet on Duke! (E3 trailer, 1998)',
    'Damn, I make this look good! (E3 trailer, 1998, reference to Men in Black)',
    'Uuuuh, that\'s what I call a close encounter! (E3 trailer, 1998, reference to Independence Day)',
    'I\'m lookin\' for some alien toilet to park my bricks... Who\'s first? (Teaser Trailer, December 19th 2007)',
    'Good, bad, I\'m the guy with the gun! (Army of Darkness, 1992)',
    'Damn it, why do they always take the hot ones?',
    'Right in the jewels.',
    'Rest in pieces.',
    'What? Did you think I? was gone forever? (A reference to the many years of development time of \'Duke Nukem Forever\' and the closure of the Duke Nukem side of 3D Realms in 2009)',
    'Hell, I\'d still hit it.',
    'Coochi-Coochi.',
    '"Hail to the King, baby!" (Reference to Army Of Darkness\'s Ash)',
    'Holsom Twin: What about the game, Duke? Was it any good? Duke: Yeah, but after 12 fucking years? it should be! (reference to Duke Nukem Forever being halted for 12 years)',
    'There\'s more where that came from.',
    'Kid: Mister Nukem, would you sign this for me? Duke Nukem: Sure kid, you might grow up to be as awesome as me.',
    'I\'ve got balls of steel.',
    'Hail to the King, baby!',
    'Suck it down!',
    'I\'m gonna rip your eye out and piss on your brain, you alien dirtbag!',
    'My job is to kick ass, not make small talk.',
    'Looks like those alien bastards drank all my beer.',
    'Not my babes! Not in my town! You alien motherfuckers are gonna pay for this!',
    'Take your pills...er...vitamins every day and you might grow up to be as awesome as me.',
    'Take your tentacles back to Japan, you freak! (after killing an Octobrain)(This is a reference to tentacle hentai.)',
    'Take those tentacles and shove \'em up your ass! (after killing an Octabrain)',
    'My balls, your face.',
    'Have a taste of my ball! (after crushing a condemned building full of enemies with the wrecking ball)',
    'All right, time for my reward! (while meeting with the Holsom Twins)',
    'Looks like those alien bastards drank all my beer.',
    '[slapping alien breasts] Got milk?',
    'Hmm... convenient.',
    'Holy shit!',
    'I\'m from Las Vegas, and I say: kill \'em all. (reference to Rico\'s quote in Starship Troopers)',
    'I guess pigs DO fly! (after causing an explosion that makes a pig-cop fly)',
    'It\'s down to you and me!',
    'It\'s good!',
    'No! Come on! No! (after grabbing the piece of crap)',
    'I\'m the Duke, I\'m A-number 1. (Reference to The Duke of New York City in Escape From New York)',
    'Now what am I doing? (after taking a piece of crap)',
    'Oh yeah! I\'m bringing sexy back. (A possible reference to Justin Timberlake\'s song \'SexyBack\')',
    'A turd in the hand is worth two in the bush. (while holding a piece of crap)',
    'Power armor is for pussies! (while looking at a suit of armor resembling that of a Master Chief\'s from HALO)',
    'Size only matters when you\'re full grown, baby!',
    'This is taking forever. Time to stop pissing around and get this big guy back into action. Woah, that water\'s cold. (while pissing at the beginning of the game, a reference to the protracted and extensive development time of \'Duke Nukem Forever\') A reference to a famous old joke involving John Holmes, the late porn star. I say this as he then adds "And deep too"',
    'Tonight, You dine in hell! (reference from the movie 300)',
    'A crowbar would come in handy right about now. (While looking at boarded mine. Reference to Gordon Freeman and the use of crowbars in Half-Life series)',
    '[after solving a gear puzzle] Duke one, gears none.',
    'Bonjour, le hot stuff.',
    'Squeal piggy! Squeal [reference to Deliverance. Could be also a reference from the first Unreal Tournament "Squeal boy, squeal!" as DNF is based on Unreal Engine]',
    'Dammit Leroy! [reference to a famous line from a World of Warcraft video called Leeeeroy Jenkins]',
    'That\'s one Dead Space marine [reference to Isaac Clarke, Dead Space\'s main character and is also an allusion to a classic line from Duke Nukem 3D in reference to Doom.]',
    'America, fuck yeah [In reference to the movie Team America]',
    'Good, Bad, I\'m the guy with the gun! [Reference to Army of Darkness as well as Blood.]',
    'Crumble like a shit cookie! [Multiplayer Quote.]',
    'I don\'t dig on swine. [Samuel L. Jackson, Pulp Fiction]',
    'Douche.',
    'I\'m going to kill you old style. [Reference to Peggy from the video Ventrilo Harassment - Duke Nukem Forever]',
    'I hate valve puzzles! [While solving a puzzle that includes pipes and valves. Reference to Half-Life ]',
    '[barrels rolling down a long stairway] Where\'s a hammer when you need one? (Reference to Donkey Kong)',
    '[after killing the foe throwing barrels] Huh, I was expecting a monkey. (Also a reference to Donkey Kong)',
    'You\'ve got a lot of guts. Let\'s see what they look like. [Small Soldiers (film)]',
    'I\'d buy this for a dollar. [Robocop (film)]',
    'Did I promise to kill you last? I lied. (Reference to Commando)',
    'Duke wins.... Fatality! [Reference to the 1992 arcade fighting game by Midway, Mortal Kombat)',
    'If it bleeds, I can kill it (Reference to Predator)',
    'What am I, a Chimpanzee? (after grabbing the piece of crap)',
    'What\'s new, pussycat? (Reference from Tom Jones "What\'s new pussycat")',
    'What kind of sick motherfucker picks up wet feces? (after grabbing the piece of crap)',
    'What the hell?',
    'Yeah, this should help.',
    'Yeehaw, motherfucker! (During the "Highway" levels)',
    'Vroom vroom, motherfucker! (During the "Highway" levels)',
    'You wanna touch it, don\'t you? (while admiring himself in the mirror)',
    '[meeting the first Battlelord] You\'re one ugly motherfucker. (Reference to Predator)',
    'I got balls of steel!',
    'Who wants white meat? Who wants it? [after killing a pig cop]',
    'Dear diary... Jackpot! [Reference to a Quagmire scene in Family Guy)',
    'Seriously, a nutless monkey can do your job (Reference to Les Grossman in Tropic Thunder.)',
    'This is gonna fuck up my hair!',
    'I\'ve got balls of fail![after losing the at the "Balls of Steel" pinball machine]',
    'Time to redecorate, in brain matter grey.',
    'Dick!',
    'Quit bleeding, pussy!',
    'Another day, another disembowelment.',
    'Just call me "Frankenstein." (After running down an enemy with the monster truck. Reference to Deathrace movie masked driver:frankenstein)',
    'Aww, and it got such good gas mileage! (After the monster truck sinks)',
    'Time to paint the town red',
    '"Die you metal motherfucker."',
    '"I\'ve got balls balls balls balls of Steel" a reference to the Duke Nukem Ventrilo Harassment youtube video.',
    '"Looks like you\'re last years model."',
    '"One more for the scrapyard."',
    '"Nothin\' but scrap metal."',
    '"Freakin\' imposter."',
    '"I hate to kick my own ass but it\'s gotta be done."',
    '"I don\'t dig on mines."',
    '"You can\'t beat the real thing baby."',
    'Often imitated never duplicated."',
    '"Damn, I wouldn\'t want to lose to me either."',
    'Why so serious?" (From the Dark Knight.)',
]

class DukeNukem < Plugin
    def help(plugin, topic="")
        "nukem => retrieve random quotes from Duke Nukem. <@bot> nukem"
    end

    def nukem(m, params)
        m.reply NUKEM.pick_one
    end
end

plugin = DukeNukem.new
plugin.map 'nukem'