MARIO = [ 
    '"Come on, \'bro, you\'re dragging."',
    '"We\'re there. All I can see are turtle tracks. Whaddaya say we give Bowser the old Brooklyn one-two?"',
    '"I\'m going in, \'bro. Those krazy Koopas must be stopped or all this will soon be puddles!"',
    '"Luigi, can\'t talk long. Bowser doesn\'t know my videophone still works for calling out. I don\'t know where he\'s keeping me. Sewage! He\'s coming back. Later!"',
    '"Yo, \'bro. Just calling to check up. Looks like Bowser is raising his prices. Seems he can\'t collect enough ransom to pay for the hairdryers since you\'ve been foiling his plans. Keep up the good work -- and get me outta here as soon as you can!"',
    '"Mama! Hoo-Hah-Hoo! Ow! Wow!"',
    '"Hoooooot!!!...hot! hot!" ',
	'"Super Mario Sunshine! Wahoo!"',
    '"Looks like a giant-"',
    '"Looks like Mario\'s gonna have to find a job."',
    '"Nice of the princess to invite us over for a picnic, eh Luigi?"',
    '"Luigi, look! It\'s from Bowser!"',
    '(reading Bowser\'s note) "Dear pesky plumbers. The Koopalings and I, have taken over the Mushroom Kingdom! The princess is now a permanent guest at one of my seven Koopa Hotels! I dare you to find her if you can!"',
    '"You know what they say: all toasters, toast toast."',
    '"We gotta find the princess!"',
    '"If you need instructions on how to get through the hotels, check out the enclosed instruction book!"',
    '"Looks kinda peaceful."',
    '"Hey, princess!"',
    '"Maybe there\'s a switch in one of the rooms! Remind me to check."',
    '"A-ha! Here\'s the problem; too many toasters! You know what they say: All toasters toast toast!"',
    '"That oughta do it!"',
    '"Where\'d she go?"',
    '"Gee, it\'s kinda dark..."',
    '"Get ready to catch her!"',
    '"It\'s hard to see through those clouds. I hope we can get rid of \'em! Get the hint?"',
    '"Hey you! Get offa my cloud!"',
    '"It\'s been one of those days... Come on, Luigi!"',
    '"We ain\'t afraid of no Koopas!"',
    '"Aha! Maybe this will keep that lizard king from playing with the doors!"',
    '"Where\'s the Princess?"',
    '"Be careful! When you pinch Wendy\'s pennies, they pinch back!"',
    '"So this is where Wendy hid the real coins!"',
    '"That wasn\'t so hard, was it?"',
    '"This is it Luigi!"',
    '"Remember, where there\'s smoke..."',
    '"You\'re the best player ever!"',
    '"Ah, that Charles Martinet! Nice Italian boy."',
    '"And thanks to all the artists, the music, people, everybody!"',
    '"All you, it\'s all you, baby!"',
    '"No, you don\'t! No, you don\'t!"',
    '"Come back here, you big monkey!"',
    '"Mario versus Donkey Kong!"',
    '"Good job!"',
    '"Ha ha! Gotcha!"',
    '"Here we go again! Hoo ho!"',
    '"Here we go! Again? Again?"',
    '"Here, you like? It\'s a Mini Mario!"',
    '"Hey! Come back here!"',
    '"Hey, Donkey Kong! Are you okay?"',
    '"Hey, it\'s okay. Don\'t cry!"',
    '"Hurry, hurry, hurry!"',
    '"Oh, you Mama Mia (Italian gibberish)"',
    '"Let\'s-a get-a going!"',
    '"Mama Mia, time\'s up! (cries)"',
    '"Oh, the engineering. Mama Mia."',
    '(whispering) "Oh yeah, don\'t forget to thank Mr. Miyamoto!"',
    '"Stop! Not again!"',
    '"Thank you very much for to playing my games-es!"',
    '"Okey dokey! (grunts) Let\'s-a go!"',
    '"Way to go!"',
    '"We did it! Good job, little guy."',
    '"What are you doing? What\'s going on here?"',
    '"Well, that was sure fun! I had a great time, hee hee!"',
    '"You know, I gotta say, it\'s nice to have a little Mini Mario!"',
    '"Let\'s-a go, little guys!"',
    '"Hey! You! Come back-a here!"',
    '"Oh-a mamma mia..."',
    '"Ow! My head!"',
    '"What are you doing?"',
    '"Let\'s get going]]" Oh, (Italian gibberish)"',
    '"Welcome to Mario Kart!"',
    '"Mario Grand Prix!"',
    '"Time Trials!"',
    '"Select the level."',
    '"Select your player."',
    '"Select map."',
    '"Hee hee! I got it!"',
    '"Yeah! Ha ha ha!"',
    '"Take it easy!"',
    '"Hey, you very good! See you next time!"',
    '"Wahoo! I\'m the winner!"',
    '"Okey-Dokey. Mario get you next time!"',
    '"It\'s-a Mario time!"',
    '"Take-a this!"',
    '"Take-a that!"',
    '"Nooooooooooooooooo!!!',
    '"Nintendo! Wahoo!"',
    '"That\'s-a so nice!"',
    '"Hooray!"',
    '"Presto!"',
    '"Wha-wha-wha-wha-WAHOO!"',
    '"Whoo-hoo! Lucky Mario!"',
    '"Fantastico!"',
    '"That\'s a great!"',
    '"Mario Kart Wii!"',
    '"Mario Time!"',
    '"Mario, yeah!"',
    '"I\'m-a gonna get you!" (when he uses a Star or Mega Mushroom)',
    '"Ohhhh. Mamma Mia!"',
    '"Oh, no. I lose."',
    '"Watch out!"',
    '"Go, Red Team!"',
    '"Oh yeah, blue team!"',
    '"Yeah, Mario wins! Wahoo!"',
    '"Mario number one! Hoho!"',
    '"Okey-dokey!! Yahahoo!!"',
    '"I got you!"',
    '"Hot hot hot hot!"',
    '"Oh hot, oh hot, hothothot!"',
    '"Yes! Yahoo!"',
    '"Oh yeah! Hoho! Wahoo!"',
    '"Bye-bye!"',
    '"Aw, mama, ohhhh!"',
    '"Okey dokey! Mario, Mario!"',
    '"Oh yeah, I did it!"',
    '"It\'s okay, I\'ll get you next time!"',
    '"Mario loses, oh ho ho ho!" (cries)',
    '"Wahoo! Ha Ha!" ',
	'"Yah-hah! I got a star!"',
    '"Yeah, Mario is the winner!"',
    '"Hoo-hoo! Mario\'s the winner!"',
    '"I\'m-a the Superstar!"',
    '"We\'re the Superstars!"',
    '"I\'m-a gonna win!"',
    '"Get me outta here!"',
    '"Ey, Luigi! What\'s the hold-up?"',
    '"Huh? Wah!"',
    '"Oooh... ah! Luigi! You save Mario! Way to go! Number 1!"',
    '"That\'s my bro."',
    '"Look out! Mario wants in on the action!"',
    'To Yoshi: "I\'ll help you find your cookies, Yoshi - just give me a second to brush these cookie crumbs out of my mustache!"',
    '"Hey, I\'m a big superstar! I should be able to roll a pretty good number!"',
    '”Not to look a gift Yoshi in the mouth, but I was hoping for more coins…”',
    '"Here we go! Let\'s see what happens next!"',
    '"Hey, everybody! You\'ve got an open invitation to stop by my shop anytime you want!"',
    '"How\'s everyone doing? I\'m feeling great! Let\'s roll!"',
    '”Come on now, little die! Give me a good roll!”',
    '"Here we go! Just remember, little die: Mario\'s your best friend!"',
    '"Rolling the die is just one of my many special talents!"',
    '"Wahoo! One more suit, and it\'s 1-Up time! I mean, level-up time!"',
    'After warping: "What a ride! That was almost as fast as traveling via pipe!"',
    'After warping:"Hey, I think I just warped! That sure was a fast trip!"',
    '"What a beautiful shop! Not too shabby for a plumber, huh?"',
    '"All right, my turn!"',
    '"Hey, that\'s pretty nice! I think I want to buy more shops around here!"',
    '"Hey, I\'m a big superstar! I should be able to roll a pretty good number!"',
    'To Player: "It\'s me, Mario! Best of luck!',
    '"Wahoo! I\'m all recharged and ready to roll! Someone give me the die!"',
    '"Oh, no! I have to sell my shop. Good-bye, dear shop of mine!"',
    '"Huh!? Where\'d all my coins go? I guess I can\'t afford to buy you right now, little property...but I\'ll be back!',
    'After building a tax office: "Watch out for the tax man, everyone!"',
    '"I\'d better see some fireworks when I level up! Woo-hoo!',
    '"I gotta remember to buy some stock next time I get a chance!"',
    '"Hey, this is a pretty nice place! It\'s good for me that you\'re not charging more to shop here!"',
    '"Wahoo! Right on the dot! Now, that\'s what I call precision!"',
    'To Luigi: "Hey Luigi! Stick with me, Bro, and we\'ll win this one together!" Luigi\'s response: "You got it, Mario! We\'ll show (Player\'s name) some real Mario Bros. teamwork!"',
    '(After landing on a Boon Square) "Hey there, lucky star! I heard you calling my name!"',
    'To Player: "You\'re off to a great start, (Player\'s name)!"',
    '"Okeydokey! One suit down, three more to go!"',
    '"It’s a race to the finish line! Start your engines!" - (about Mario Circuit)',
    '"Brr! This ship gives me the creeps! Best to win fast so I don\'t have to hang out here too long!" (about The Ghost Ship)',
    '"I wonder if there are coins in these ruins... I\'m gonna grab as many as I can!"',
    '"Uh-oh! Lava\'s never fun! It always brings back bad memories for me..."',
    '"Looks like a lot of folks came out to see today\’s game. I\’d like to knock this one out of the park!" (about Mario Stadium)',
    '"Wow! What a fancy palace! But I still think Peach\’s Castle is the best..." (about Castle Trodian)',
    '"Whoa, this place is gonna make my head spin! But, hey... what a view!"',
    '"Ah, it\’s all my little Yoshi friends! How have you been, guys?"',
    '"Dooo-doo-doo-doo-doo-dooooo! Hey, I love this tune!" (about the Super Mario Bros. theme)',
    '"Oh no! Nothing good ever comes out of this creepy castle. I hope I can escape safe and sound!" (about Bowser\'s Castle)',
    '"Slimes everywhere! That’s O.K., I suppose… as long as they aren\’t bad slimes!"',
    '"I guess Erdrick is the big cheese around these parts! I tip my hat to you, legendary hero!"',
    '"Ha ha! I guess this is the place where I can change my profession... Thanks, but I\’m happy being a plumber AND a hero!" (about Alltrades Abbey)',
    '"Oh boy, another galactic adventure! Here we go, sailing through space!" (about Starship Mario)',
    'To Birdo: "Shopping here is a bargain, Birdo!"',
    'To Birdo: "Ouch! Birdo, you\’re charging me an arm and a mustache! That\’s precious gold I\’m never going to see again!"',
    'To Birdo: "This is gonna smart, Birdo! Why do you need to charge so much just to shop here!"',
    'To Birdo: "Birdo, have I got a deal for you! We\’ll both come out ahead if we swap shops!"',
    'To Birdo: "We\’re all proud of you, Birdo! Get a move on and collect your prize!"',
    'To Bowser: "Hey, Bowser! Maybe you\’re not such a bad guy after all! Your shop is cheap, at least!"',
    'To Bowser: "Oh no! There go my gold coins! I worked hard for those, Bowser!"',
    'To Bowser: "Mamma mia! This place is way too pricey for a simple plumber!"',
    'To Bowser: "I don\’t want to do this…but I think we\’re going to have to work together! Let\’s swap shops , enemy of mine!"',
    'To Bowser: "Don\’t think I\’m going to let you win that easily, Bowser!"',
    'To Bowser Jr.: "I\’m grateful that you\’re not charging too much, Bowser Jr., but I still don’t like giving you my hard-earned gold!"',
    'To Bowser Jr.: "I\’m surprised you\’re charging folks so much to shop here, Bowser Jr. ! Just like your daddy, you are!"',
    'To Bowser Jr.: "Mamma mia! I don’t know if I can afford these prices!"	',
    'To Bowser Jr.: "I don’t want to do this…but I think we\’re going to have to work together."',
    'To Bowser Jr.: "Bowser Jr.! You\’re just like your daddy. Always getting in my way!"',
    'To Daisy: "Uh-oh! Come back, my beautiful gold coins! Ah well… I suppose it could be worse, right?"',
    'To Daisy: "Oh, Princess Daisy! Why do you need to charge so much to shop here? I\’m not sure it\’s worth it!"',
    'To Daisy: "Why bother earning money if I\’m just gonna end up throwing it away like this?"',
    'To Daisy: "Yoo hoo, Princess Daisy! I\’ve got a nice deal for you! Take a look!"',
    'To Daisy: "This is gonna be a big win for you, Princess Daisy! You must be so proud!"',
    'To Diddy Kong: "Ah! This is reasonably priced shop! I\’m surprised you\’re not charging an arm and a banana, Diddy Kong!"',
    'To Diddy Kong: "Boo! That\’s a bad Kong!! A very bad Kong!"',
    'To Diddy Kong: "Ouch ouch ouch! Why don\’t you just throw a barrel at me? That would hurt less than giving you so many of my gold coins!"',
    'To Diddy Kong: "Don\’t believe everything Donkey Kong has told you about me, Diddy Kong. I\’m a nice guy! I just want to trade shops!"',
    'To Diddy Kong: "Mamma mia! You\’ve got everything you need to win, Diddy Kong! Am I really going to lose?"',
    'To Donkey Kong: "Hey, Donkey Kong! Would you mind if I paid you in bananas? Ha ha ha! Oh, I bet you get that joke all the time!"',
    'To Donkey Kong: "Oh boy ! I was saving those coins to buy myself something special. Thanks a bunch of bananas, Donkey Kong!"',
    'To Donkey Kong: "Do you really need to take my gold coins, Donkey Kong? Can’t I just write you an I.O.U.?"',
    'To Donkey Kong: "Heya! Want to trade shops, Donkey Kong? C\’mon, don’t make me jump over barrels!!"',
    'To Donkey Kong: "You sure know how to roll that die, Donkey Kong! Almost as well as you roll a barrel!"',
    'To Luigi: "Hey, Bro! I\’m glad to see your shop isn\’t too expensive. Now I\’m glad I dropped by!"',
    'To Luigi: "Hey, Bro! I can\’t believe you\’re charging these kinda prices! They\’re a bit high, don\’t you think?"',
    'To Luigi: "Oh, Luigi! Can’t you give me a special discount or something? I thought we were the bestest of buddies!"',
    'To Luigi: "PSSST! Hey, Bro! You want to get ahead? I’ve got a plan! Let\’s trade shops!"',
    'To Luigi: "Great job, Bro! Ha ha! You\’re my hero!"',
    'To Peach: "Thanks for not charging me too much for shopping here, Princess Peach! You\’re one of the good ones!"',
    'To Peach: "Uh-oh! Peach, do you really expect me to pay that much just to shop here? I thought we were friends!"',
    'To Peach: "Not very nice, Princess Peach! Not very nice at all!"',
    'To Peach: "Oh, Princess Peach! Trade shops with me, won\’t you? It\’s a good deal for both of us!"',
    'To Peach: "Looks like I need to start picking some flowers for your victory bouquet, Princess Peach!"',
    'To Toad: "Whew! I sure am lucky that your shop isn\’t too pricey, Toad!"',
    'To Toad: "Whoa! What an expensive shop! That’s just about the last thing I need today!"',
    'To Toad: "You need to have a sale, Toad! Your prices are out of this world!"',
    'To Toad: "Let\’s make a deal, Toad. Swapping shops will give us both a leg up!"',
    'To Toad: "My good friend! Where\’s your sportstoadship? How can you make a break for the goal without even helping me?"',
    'To Waluigi: "Oopsy-daisy! I wasn\’t planning on stopping here. At least I\’m not going to have to shell out too many gold coins!"',
    'To Waluigi: "Why, Waluigi, why!? You\’ve got no good reason to charge so much just to shop here!"',
    'To Waluigi: "Go on, Waluigi! Take me money and run, you greedy man!"',
    'To Waluigi: "I hate to fraternize with my brother\’s nemesis, but it looks like we’re going to have to work together! Let\’s swap shops, Waluigi!"',
    'To Waluigi: "What!? Waluigi\’s about to win!? I don’t think Luigi is going to be too happy about that…"',
    'To Wario: "I\’m surprised your shop is so cheap, Wario! I guess I should be grateful you\’re not being too greedy, huh?"',
    'To Wario: "I sure hate to give you so many of my gold coins, Wario! You won’t be too happy until I\’m completely bankrupt!"',
    'To Wario: "Getting greedier by the minute, aren’t you, Wario?"',
    'To Wario: "You\’re a greedy one, Wario, but maybe that\’ll come in handy today. Trade shops with me, and we\’ll both be winners!!"',
    'To Wario: "Are those coins I hear ratting around in your pockets, Wario!? Looks like you might win this one!"',
    'To Yoshi: "Yoshi! I\’m glad I stopped by. Shopping here isn\’t as expensive as I thought it was going to be!"',
    'To Yoshi: "Oh boy, Yoshi! I hope you’re saving up all the money you make from this shop, \‘cause it sure is pricey!"',
    'To Yoshi: "Yoshi! After everything I\’ve done for you!?"',
    'To Yoshi: "Yoshi, my friend! Trade shops with me, and we\’ll both come out ahead!"',
    'To Yoshi: "Hey, Yoshi! You\’re gonna share all that gold with me if you win, right? C\’mon, I thought we were buddies!"',
    '"It\'s-a me! I\'ve been on fire lately, but I hope you\'ll challenge me!"',
    '"Mario Golf: Toadstool Tour! Woo-hoo!"',
    '"Achoo! Excuse me!',
    '"Hey paesanos, it\'s The Super Mario Bros. Super Show!" - Opening Credits',
    '"Do the Mario!" - Closing Credits',
    '"I hate to run on an empty stomach!" - "The Bird! The Bird!"',
    '"Must be a beehive nearby, and when there\'s bees; there\'s raviolis smothered with honey" - "King Mario of Cramalot"',
    '"If Toad doesn\'t get us outta here soon, I\'m gonna eat this mattress!" - "Butch Mario & the Luigi Kid"',
    '"Wake up, Luigi! The only time plumbers sleep on the job, is when we\'re working by the hour!" - "Butch Mario & the Luigi Kid"',
    '"Catfish pizza? This may be a first, but I\'m not hungry!" - "Rolling Down the River"',
    '"Excuse my brother, he gets nervous around guys six times bigger than him." - "The Great Gladiator Gig"',
    '"We can fix anything if there\'s spaghetti involved!" - "The Great Gladiator Gig"',
    '"Hey, Koopa! I hope your Big and Tall shop blows up, with you in it!" - "Mario and the Beanstalk"',
    '"Those ain\'t wedding bells in your tower! They\'re bats in your belfry!" - "Love \'Em and Leave \'Em"',
    '"Hey! Where\'d you learn how to ride a bike!?" - "The Great BMX Race"',
    '"Get back here, Koopa! Don\'t you know vegetables are good for you?" - "The Great BMX Race"',
    '"Not on my melted mozarrella! - "Stars in Their Eyes"',
    '"If food isn\'t pasta, it doesn\'t count!" - "Jungle Fever"',
    '"Unstoppable? We\'re plumbers! If we can unstop a stop, we can stop the unstoppable!" - "The Fire of Hercufleas"',
    '"Magnifico! You\'re stronger than Grandma Mia\'s garlic chip cookies!" - "The Fire of Hercufleas"',
    '"Faster than a vanishing clog! More powerful than an electric drainsnake! It\'s Super Mario!" - "Pirates of Koopa"',
    '"If you can\'t beat \'em, join \'em! Then beat \'em!" - "Pirates of the Koopa"',
    '*singing* "Hush, little Princess, don\'t you cry. I\'m gonna buy you a pizza pie. And if that pizza pie gets ate, Luigi\'ll buy you a New York steak." - "Two Plumbers and a Baby"',
    '"This is the first time my lunch ever took a bite out of me!" - "The Adventures of Sherlock Mario"',
    '"I just love food that\'s spicy!" - "On Her Majesty\'s Sewer Service"',
    '"I always cry at wedding feasts!" - "Mario and Joliet"',
    '"Koopa\'s gonna take a trip he didn\'t plan on!" - "Too Hot to Handle"',
    '"I hope the food\'s better than the furniture!" - "Mighty McMario and the Pot of Gold"',
    '"As we say in Brooklyn; Banzai!" - "Mario Meets Koop-zilla"',
    '"Save the spaghetti! Save the spaghetti!" - "Mario and the Red Baron Koopa"',
    '"Koopone, you\'ve Kooped your last Koop!" - "The Unzappables"',
    '"It doesn\'t look good for the good guys, Luigi!" - "The Mark of Zero"',
    '"I guess Mexican food doesn\'t agree with El Koopitan!" - "The Mark of Zero"',
    '"When Luigi\'s unfrozen, he\'s goin\' on a diet!" - "The Koopas Are Coming! The Koopas Are Coming!"',
    '"It\'s ugly, but it floats!" - "The Trojan Koopa"',
    '"What? Only one pizza?" - "Quest for Pizza"',
    '"The Mushroom People get the mine, and Koopa gets the shaft!" - "The Great Gold Coin Rush"',
    '"When the plumbing gets tough, the tough get plumbing!" - "Plumbers Academy"',
    '"Me Marzan! King of the jungle!" - "Mario of the Apes"',
    '"Can\'t we discuss this man to Mouser?" - "Princess, I Shrunk the Mario Brothers"',
    '"First, we\'d better get inside by a fire, before we turn into pastasicles!" - "Little Red Riding Princess"',
    '"The Provolone Ranger is ready to ride. High ho, Ostro, away!" - "The Provolone Ranger"',
    '"Help, help! There\'s a big, ugly spider in here! Help! My yelling\'s gonna keep you up all night, unless you get this spider outta here!" - "Escape from Koopatraz"',
    '"Luigi, are you a man or a Mouser?" - "Mario of the Deep"',
    '"I guess someday, even Super Mario can\'t think of everything!" - "Flatbush Koopa"',
    '"Don\'t count your reptiles before they\'re hatched, lizard lips!" - "Raiders of the Lost Mushroom"',
    '"I was hoping we\'d have lunch, not be lunch!" - "Crocodile Mario"',
    '"I just love playin\' Koopa in the middle!" - "Crocodile Mario"',
    '"I just had the strangest dream. I was a TV dinner!" - "Star Koopa"',
    '"He\'s showing a plumber how a garbage disposal works?" - "Star Koopa"',
    '"Watch it, gang! His toes are loaded!" - "Robo Koopa"',
    '"Ahh! Reptile breath tornado! I\'m a goner!" - "Sneaky Lying Cheating Giant Ninja Koopas"',
    '"You\'re not taking over any land, you Bowser Koopa!" - "Sneaky Lying Cheating Giant Ninja Koopas"',
    '"Just what we need, a Miserable Squawking Angry Giant Ninja Parrot." - "Sneaky Lying Cheating Giant Ninja Koopas"',
    '"We better get that mummy back where it belongs, before it scares the pasta outta everybody!" - "Mind Your Mummy Mommy, Mario"',
    '"Yuck! A hug from her could be bad for my health! I\'d better scram!" - "Mind Your Mummy Mommy, Mario"',
    '"I like long naps, but not that long!" - "Mind Your Mummy Mommy, Mario"',
    '"I can\'t sleep for ten-thousand years. I\'ll get too hungry!" - "Mind Your Mummy Mommy, Mario"',
    '"Wrench attack, Luigi! Let\'s tool on outta here!" - "Princess Toadstool for President"',
    '"No more Mr. Nice Guy!" - "Princess Toadstool for President"',
    '"Bob-ombs! Next to Koopa himself, they\'re my most unfavorite things!" - "Never Koop a Koopa"',
    '"Give it up! We already flew the Koopa!" - "Never Koop a Koopa"',
    '"Tea? With Koopa? Princess, how can you be so nice to Bowser Koopa?" - "Reign Storm"',
    '"Don\'t be a baby, Luigi." - "Toddler Terrors of Time Travel"',
    '"Invincible Stars? Invincible timing, Princess!" - "Tag Team Trouble"',
    '"Looks like I\'m plumber out of luck!" - "Oh, Brother!"',
    '"Brothers. Ya can\'t live with \'em. Ya can\'t live without \'em. - "Oh, Brother!"',
    '"Aw, meatballs! The TV\'s on the blink! - "Misadventure of Mighty Plumber"',
    '"Take a look, Toad. One Super Mario turn of the wrench, and all that stopped up water will run out of your tub faster than Invincible Mario!" - "A Toadally Magical Adventure"',
    '"Le\'s show that big bad Boom Boom some of our patented Super Mario super moves!" - "Misadventures in Babysitting"',
    '"QUIET! You wanna wake the dead? You don\'t want Koopa to find out we\'re in his kingdom, do ya?" - "Do the Koopa"',
    '"I never saw so many tonsils in all my life!" - "Kootie Pie Rocks"',
    '"Sounds like you Mushroomers are spreading mush-rumors." - "Mush-Rumors"',
    '"I\'d rather face a thousand Koopas than one mermaid mackerel with marraige on her mind! But you can\'t run from your problems forever!" - "The Ugly Mermaid"',
    '"I\'d rather marry a fish than swim with one, Luigi." - "The Ugly Mermaid"',
    '"I\'m just too chicken to be a frog!" - "The Ugly Mermaid"',
    '"Brave men die a single death; cowards marry fish-head mermaids!" - "The Ugly Mermaid"',
    '"We have been king-sized colossal jerks!" - "True Colors"',
    '"Garbage, garbage, on our stoopa, get out of here and go back to Koopa!" - "Recycled Koopa"',
    '"Hey, Luigi. Never challenge me to a game of underwater horseshoes." - "The Venice Menace"',
    '"This is no time to be Italian, Luigi! Be Polish!" - "The Venice Menace"',
    '"Aww, without super powers, we\'re no match for Super Koopa!" - "Super Koopa"',
    '"It\'s a stone, Luigi! You didn\'t make it!" - Upon seeing Luigi\'s "Football", "The Yoshi Shuffle"',
    '"And there\'s this nice guy named Santa Claus, who brings presents to all the kids who\'ve been good!" - "The Night Before Cave Christmas"',
    '"Now go home and eat some vegetables, Dr. Mario\'s orders!" - "King Scoopa Koopa"',
    '"Ugh. Now I know how meatball feels..." - Upon being eaten by Yoshi, "Mama Luigi"',
    '"You didn\'t tell me you were bringing a secret weapon, Luigi!" - "Mama Luigi"',
    '"Mama? MAMA LUIGI?!? <laughs>" - "Mama Luigi"',
    '"When the going gets tough, the tough read Dirk Drain-Head!" - "Bedtime for Drain-Head"',
    '"Tea hea... I mean, tee hee!" - "Cloud Nine"',
    '"But I\'ve got drains to drain! Clogs to unclog! Remember... the noble plumber always comes through? Besides, this coat is turning my hair brown!" - "The Doctor Is In... Over His Head"',
    '"Eat cake, shell scum!" - "Super Mario Adventures"',
    '"I wish Luigi were here, I could blame him!" - "You Again?"',
    '"Oh, no! The Princess is being forced to listen to a debate by two Fryguys about the names for the little things on the end of your shoelaces! What do you call those little things anyway? Tabs? End caps? Plastic nobbie deals?" - "You Again?"',
    '"Stay away, you guys. I overslept, and I have to save the Princess!" - "You Again?"',
    '"Oh no! It\'s a pipe-o-rama!" - "Super Mario Adventures',
    '"You sure that kid\'s on your side?" - "The Buddy System',
    '"A-meecal! It\'s-a my pleasure! Hello, everyone! It\'s-a me, Mario, wahoo! Hello! Hello! Ha ha."',
    '"Well, ameegal, first, I\'m-a want to say, thank you very much for everyone who made this-a moment possible. The Princess-a Peach, my right hand man Luigi, and the best adviser in the business, Toad. So, starting today, I\'m-a super duper excited to be taking my talents to the Mushroom Kingdom in my new game, Mario Sports Mix. Woohoo!" ',
    '"Well, I\'m-a telling Nintendo, we need to make this game super duper! And they said, \'Oh, okey dokey, uh how about-a two sports?\' I\'m-a said, \'Nah\', so they said, \'Uh, how about-a three?\' and I said, \'That\'s okay. But, have you thought about-a four sports-a featuring over the top-a super duper moves with none other than me, Mario?\' Woohoo!"',
    '"Ah, well, the hardest part was to get all of these all stars on aboard-a. Some, they were easy. Toad, he\'s always-a hanging around, giving me advice. And-a Luigi, well, he\'s my bro; he\'s got nothing to do, and he was up for it. Then, I saved-a Princes Peach and-a Daisy, and I got-a Bowser while I was-a there. Wario, ah, he was-a hard because-a he\'s-a cuckoo crazy! But once I\'m-a mentioned it was not just the volleyball, basketball, and-a hockey, but also the dodgeball, ah ha! He was all set! In fact, I think he said-a, \'I\'ll do it. Have a rotten day *raspberries*.\' Something like-a that."',
    '"Woohoo! Fire it away! I\'m-a ready for anything!"',
    'Responding to "Is it hard to balancing your sports training with princess saving?": "Ha ha ha! Well, I got-a good news! Princess-a Peach (sighs contently), she hasn\'t been captured for a while. It\'s our-a longest-a streak-a yet-a. So, Mario\'s had more time to focus on-a saving the spikes-a and a goals in-a hockey! Ah ha!"',
    'Responding to "I have to imagine Princess saving is quite a work-out, though, too." "Oh, yeah, it\'s a great year-round workout. Mario highly recommends it. Mmm-hm!"',
    'Responding to "We\'ve seen you on the tennis and basketball courts, the diamond, and even on the race track. Which of these new sports excite you the most?": "Hmm! That\'s-a good question. It has to be... dodgeball! I\'ve been always a real fireballer with a shell, or even, the fireballs. Hee hee! So I knew I would be a natural. But, I noticed some of my friends-es are-a taking shots at-a me! Heart-a shots from Princess-a Peach-a, rainbow throws from my old pal Yoshi, and even a few vacuum whizzers sent at me by my fratelo, Luigi! Oh!"',
    'Reaction to Luigi\'s "I\'m-a tired of-a being Player 2. It\'s-a my time to shine!": "Ah, Luigi! Ah ha! He\'s probably taken out of-a context. He loves being my sidekick, hee hee hee!"',
    '"Gee, that\'s funny."',
    '"Yeah, now here\'s a good impression, here: boy, that Sony, it\'s fantastic! *nose extends* How\'s that? You don\'t like my impression?"',
    '"Okey dokey, here comes another one, ready? This is a whole movie. \'But Rhett, what about-a me?\' \'Eh, frankly, a-Scarlett-a, I don\'t give a *1-up noise*.\'"',
    '"You want to hear another one? This one here: Here\'s-a Johnny! I\'m not going to hurt you, Wendy, I\'m going to break your *coin noise* neck. You get to hear it? I\'m going to break your *coin noise* neck.',
    '"Oh, that\'s all right, I don\'t give a *coin noise*. A gold coin."',
    '"You guys want to hear another impression on a movie? Here comes a good movie; this is a good movie. *Darth Vader noises* \'Luke-ee, come and join the Dark-a Side of the Force!\' \'No thank you!\' \'Luke-ee! I\'m-a you papa!\' \'Naw! You not my papa!\' \'Yes! I\'m-a you papa!\' \'Naw! You not-a my papa!\' \'I\'m-a you papa!\' \'You not my papa!\' \'I\'m-a you papa!\' \'You not my papa!\' \'I\'m-a you papa!\' \'You not my papa!\' \'Stop saying I\'m not you papa, you little brat, I\'m-a gonna chop your hand off with a saber sword!\' Chop! \'Oh, papa! Why you chop my hand off with a laser sword! Man!\'"',
    '"Yeah, if I take that show on the road that\'s they don\'t come back"',
    '"Hey, what do you think... wasn\'t that the best impression of Gone With the Wind you\'ve ever seen?"',
    '(responding to a girl\'s question that Luigi should join the Ghostbusters group) "Hey! That\'s a pretty good idea! I think he\'d be too afraid, you know; if he had to do that every day... yeah, he\'d be under the bed after. The other night, I was sitting there, watching the Pokémon movie with him, we take the popcorn, and all of a sudden, it gets to a scary part, a scary part in the Pokémon movie, ahem, and I say, \'Hello, popcorn? Where the popcorn? Yoohoo, popcorn, where\'d you go? Wait a minute, what happened to Luigi? Lui-!\' and I saw his little feet hanging out between the cushions; he got scared; he jumped between the cushions and took the popcorn! I\'m like \'C\'mon, Luigi! I don\'t care if you\'re scared, the popcorn is not that scared.\' For crying out loud!"',
    '"What\'s my last name? That\'s-a very good question! Uh...uh... that\'s right! My name\'s-a Mario Mario. Of course, my brother\'s name, a-Luigi Mario. And of course, my mama\'s-a Mama Mia Mario; my papa Papa Pio Mario. Of course, my grandmama Grandmama Mia Mario and my greatpapa et cetera, et cetera. Yeah, first name Mario, last name Mario. Yahoo!"',
    '(responding to a question about using cement shoes on Sonic)"I don\'t believe in using cement shoes for my friends, ah ha ha ha."',
    '(responding to "How do you feel about Bowser being in Wreck-it Ralph, but not you?") Bu-bu-bu-bu Bowser\'s in a movie, but...? Ooo... I... Gee, I don\'t mind. *whimpers and cries* No, no, it\'s okay, I want Bowser to be a star. If he\'s busy being a star, then he won\'t be kidnapping the princess quite so much-a.',
    '"I do like jumping on the mushrooms. I also like picking up the turtle shells and-a throwing them at all the little Goombas." ',
]

class MarioBros < Plugin
    def help(plugin, topic="")
        "mario => retrieve random quotes from MarioBros."
    end

    def mario(m, params)
        m.reply MARIO.pick_one
    end
end

plugin = MarioBros.new
plugin.map 'mario'